name: E2E Chromium

on:
  workflow_call:

jobs:
  e2e-chromium:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-env

      - name: Download extension
        uses: actions/download-artifact@v4
        with:
          name: extension-chrome
          path: extension/chrome

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e:chromium
